spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #配置eureka注册中心地址
server:
  port: 8081
env:
  env-update-remark-continue-update
girl:
  name: xiaoming,xiao`ou
  age: 22,22.5
